name: 'Bolt Build Setup Steps'
description: 'Executes necessary commands to setup environment for the bolt build'
runs:
  using: "composite"
  steps:
    - name: Install Bolt dependencies
      shell: bash
      run: |
        ./scripts/install-bolt-deps.sh

    - name: Setup conan profile
      shell: bash
      run: |
        python3 scripts/configure-conan-profile.py \
          --compiler clang \
          --libcxx libstdc++11 \
          --linker mold \
          --lto none  && \
        echo "core.download:parallel=1" >> ~/.conan2/global.conf

    - name: Add CI conan remote
      shell: bash
      run: |
        conan remote add ci http://conanserver:9300
